### ISSUE TITLE
BLD: compile error with NumPy main and Cython 3.0.8

### ISSUE THREAD

**Issue by tylerjereddy** [MDAnalysis/mdanalysis#4460]
On x86_64 Linux on latest `develop` I see build errors like this:

```
  /usr/bin/gcc -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -fPIC -I/home/treddy/python_venvs/py_311_mda/lib/python3.11/site-packages/numpy/_core/include -I/home/treddy/python_venvs/py_311_mda/include -I/home/treddy/github_projects/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-11.3.0/python-3.11.2-4qncg2nqev5evxfmamde3e6rnb34b4ls/include/python3.11 -c MDAnalysis/coordinates/timestep.cpp -o build/temp.linux-x86_64-cpython-311/MDAnalysis/coordinates/timestep.o -O3 -funroll-loops -fsigned-zeros -std=c++11
  In file included from /home/treddy/python_venvs/py_311_mda/lib/python3.11/site-packages/numpy/_core/include/numpy/ndarraytypes.h:1894,
                   from /home/treddy/python_venvs/py_311_mda/lib/python3.11/site-packages/numpy/_core/include/numpy/ndarrayobject.h:12,
                   from /home/treddy/python_venvs/py_311_mda/lib/python3.11/site-packages/numpy/_core/include/numpy/arrayobject.h:5,
                   from MDAnalysis/coordinates/timestep.cpp:1234:
  /home/treddy/python_venvs/py_311_mda/lib/python3.11/site-packages/numpy/_core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     17 | #warning "Using deprecated NumPy API, disable it with " \
        |  ^~~~~~~
  In file included from /home/treddy/python_venvs/py_311_mda/lib/python3.11/site-packages/numpy/_core/include/numpy/arrayobject.h:5,
                   from MDAnalysis/coordinates/timestep.cpp:1234:
  MDAnalysis/coordinates/timestep.cpp: In function ‘int __pyx_pf_10MDAnalysis_11coordinates_8timestep_8Timestep_13has_positions_2__set__(__pyx_obj_10MDAnalysis_11coordinates_8timestep_Timestep*, PyObject*)’:
  MDAnalysis/coordinates/timestep.cpp:6731:25: error: cannot convert ‘PyObject*’ {aka ‘_object*’} to ‘const PyArrayObject*’ {aka ‘const tagPyArrayObject_fields*’}
   6731 |       PyArray_FILLWBYTE(__pyx_t_3, 0);
        |                         ^~~~~~~~~
        |                         |
        |                         PyObject* {aka _object*}
```

I bisected NumPy to this commit:

```
404b23bf2df50e4822fb36f04511cb38e672e839 is the first bad commit
commit 404b23bf2df50e4822fb36f04511cb38e672e839
Author: Sebastian Berg <sebastianb@nvidia.com>
Date:   Thu Feb 8 12:27:06 2024 +0100

    MAINT,API: Always export static inline version of array accessor.
    
    While we might not hide the struct fully by default, I don't think
    there is a reason to not only export the static inline versions of
    these?
    
    They will type check a bit nicer (might give warnings), but otherwise
    should only matter if you do `PyArray_NDIM(arr) = 3`.

 doc/release/upcoming_changes/25789.c_api.rst |  3 +++
 numpy/_core/include/numpy/ndarraytypes.h     | 36 ----------------------------
 2 files changed, 3 insertions(+), 36 deletions(-)
 create mode 100644 doc/release/upcoming_changes/25789.c_api.rst
```

**Comment by tylerjereddy** [comment]
Sebastian is away for a week or two I think, I did notice that we make `PyArray..` calls right in our Cython code.

**Comment by hmacdope** [comment]
I am happy to have a look (I wrote the timestep numpy C API code), but as you say, may need review upstream. Is there a better way to do this now than the C API or should it still be stable?

**Comment by tylerjereddy** [comment]
Resolved upstream, I confirmed we can compile again in my review there.
