### PR TITLE
fix cython 2.8 compiler error

### LINKED ISSUE #1830: cython 0.28 breaks build
### Expected behaviour
After upgrade to cython 0.28 MDAnalysis should build.

### Actual behaviour
It fails (on travis) and locally (here: macOS):
```
Attempting to autodetect OpenMP support... Did not detect OpenMP support.
No openmp compatible compiler found default to serial build.
Will attempt to use Cython.
Compiling MDAnalysis/lib/formats/libdcd.pyx because it changed.
Compiling MDAnalysis/lib/c_distances.pyx because it changed.
Compiling MDAnalysis/lib/c_distances_openmp.pyx because it changed.
Compiling MDAnalysis/lib/qcprot.pyx because it changed.
Compiling MDAnalysis/lib/formats/libmdaxdr.pyx because it changed.
Compiling MDAnalysis/lib/formats/cython_util.pyx because it changed.
Compiling MDAnalysis/analysis/encore/cutils.pyx because it changed.
Compiling MDAnalysis/analysis/encore/clustering/affinityprop.pyx because it changed.
Compiling MDAnalysis/analysis/encore/dimensionality_reduction/stochasticproxembed.pyx because it changed.
[1/9] Cythonizing MDAnalysis/analysis/encore/clustering/affinityprop.pyx

Error compiling Cython file:
------------------------------------------------------------
...
"""
from ..utils import TriangularMatrix
import logging
import numpy
cimport numpy
cimport caffinityprop
       ^
------------------------------------------------------------

MDAnalysis/analysis/encore/clustering/affinityprop.pyx:32:8: 'caffinityprop.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
    # Prepare input and ouput arrays
    cdef numpy.ndarray[numpy.float32_t,  ndim=1] matndarray = numpy.ascontiguousarray(s._elements, dtype=numpy.float32)
    cdef numpy.ndarray[long,   ndim=1] clusters   = numpy.zeros((s.size),dtype=long)

    # run C module Affinity Propagation
    iterations = caffinityprop.CAffinityPropagation( <float*>matndarray.data, cn, lam, max_iterations, convergence, noise, <long*>clusters.data)
                             ^
------------------------------------------------------------

MDAnalysis/analysis/encore/clustering/affinityprop.pyx:100:30: cimported module has no attribute 'CAffinityPropagation'

Error compiling Cython file:
------------------------------------------------------------
...
    # Prepare input and ouput arrays
    cdef numpy.ndarray[numpy.float32_t,  ndim=1] matndarray = numpy.ascontiguousarray(s._elements, dtype=numpy.float32)
    cdef numpy.ndarray[long,   ndim=1] clusters   = numpy.zeros((s.size),dtype=long)

    # run C module Affinity Propagation
    iterations = caffinityprop.CAffinityPropagation( <float*>matndarray.data, cn, lam, max_iterations, convergence, noise, <long*>clusters.data)
                             ^
------------------------------------------------------------

MDAnalysis/analysis/encore/clustering/affinityprop.pyx:100:30: Compiler crash in AnalyseExpressionsTransform

ModuleNode.body = StatListNode(affinityprop.pyx:28:0)
StatListNode.stats[6] = StatListNode(affinityprop.pyx:37:0)
StatListNode.stats[0] = CompilerDirectivesNode(affinityprop.pyx:37:0)
CompilerDirectivesNode.body = StatListNode(affinityprop.pyx:37:0)
StatListNode.stats[0] = DefNode(affinityprop.pyx:37:0,
    doc = 'Affinity propagation clustering algorithm. This class is a Cython wrapper around the Affinity propagation algorithm, which is implement as a C library (see ap.c). The implemented algorithm is described in the paper:\n\n    Clustering by Passing Messages Between Data Points.\n    Brendan J. Frey and Delbert Dueck, University of Toronto\n    Science 315, 972–976, February 2007\n\n    Parameters\n    ----------\n    s : encore.utils.TriangularMatrix object\n        Triangular matrix containing the similarity values for each pair of\n        clustering elements. Notice that the current implementation does not\n        allow for asymmetric values (i.e. similarity(a,b) is assumed to be\n        equal to similarity(b,a))\n    preference : numpy.array of floats or float\n        Preference values, which the determine the number of clusters. If a\n        single value is given, all the preference values are set to that.\n        Otherwise, the list is used to set the preference values (one value per\n        element, so the list must be of the same size as the number of\n        elements)\n    lam : float\n        Floating point value that defines how much damping is applied to the\n        solution at each iteration. Must be ]0,1]\n    max_iterations : int\n        Maximum number of iterations\n    convergence : int\n        Number of iterations in which the cluster centers must remain the same\n        in order to reach convergence\n    noise : int\n        Whether to apply noise to the input s matrix, such there are no equal\n        values. 1 is for yes, 0 is for no.\n\n    Returns\n    -------\n    elements : list of int or None\n        List of cluster-assigned elements, which can be used by\n        encore.utils.ClustersCollection to generate Cluster objects. See these\n        classes for more details.\n\n    ',
    modifiers = [...]/0,
    name = 'AffinityPropagation',
    np_args_idx = [...]/0,
    num_required_args = 5,
    py_wrapper_required = True,
    reqd_kw_flags_cname = '0',
    used = True)
File 'ExprNodes.py', line 5213, in infer_type: SimpleCallNode(affinityprop.pyx:100:51,
    result_is_used = True,
    use_managed_ref = True)
File 'ExprNodes.py', line 6704, in infer_type: AttributeNode(affinityprop.pyx:100:30,
    attribute = 'CAffinityPropagation',
    is_attribute = 1,
    needs_none_check = True,
    result_is_used = True,
    use_managed_ref = True)

Compiler crash traceback from this point on:
  File "/Users/oliver/anaconda3/envs/mda_develop/lib/python3.6/site-packages/Cython/Compiler/ExprNodes.py", line 6704, in infer_type
    return node.entry.type
AttributeError: 'NoneType' object has no attribute 'type'
Traceback (most recent call last):
  File "setup.py", line 482, in <module>
    exts, cythonfiles = extensions(config)
  File "setup.py", line 372, in extensions
    extensions = cythonize(pre_exts)
  File "/Users/oliver/anaconda3/envs/mda_develop/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1026, in cythonize
    cythonize_one(*args)
  File "/Users/oliver/anaconda3/envs/mda_develop/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1146, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: MDAnalysis/analysis/encore/clustering/affinityprop.pyx
```

### Code to reproduce the behaviour
```bash
conda upgrade --all
cd package
python setup.py build
```

### Currently version of MDAnalysis:
develop

(run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)

### PR DESCRIPTION
**Pull request by kain88-de**
Fixes #1830

Changes made in this Pull Request:
 - I'm not sure what the actual error was. But only one function is imported and
the cleaner solution long-term is to skip the pxd file and directly import from
c.

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [x] CHANGELOG updated?
 - [x] Issue raised/referenced?

### CODE REVIEW

**Comment by mtiberti** [comment]
I'm about to push a fix for the other compilation error in ENCORE - I basically did the same that @kain88-de did for the other one. It should be a step forward, even though the compiler then complains about other parts of the code locally so I wouldn't expect this build to pass

**Comment by kain88-de** [comment]
this worked locally with the newest cython version. Let's see if we are lucky

**Comment by zemanj** [comment]
@kain88-de @orbeckst @richardjgowers undo #1835 and it should work with cython 0.28?!

**Comment by kain88-de** [comment]
@zemanj just undoing the band-aid won't make the build work with cython 0.28. There are more fixed we need to apply. This will take some time to figure out.

**Comment by tylerjereddy** [comment]
The SciPy team opened [an issue](https://github.com/cython/cython/issues/2154) on the Cython tracker for 0.28, although we only see problems with Windows (appveyor) builds at the moment.

**Comment by kain88-de** [comment]
our problem is that cython only builds the object files but doesn't link to a shared library object file that can be imported into a python session.

File: package/MDAnalysis/analysis/encore/dimensionality_reduction/stochasticproxembed.pyx [hunk 1]
```diff
@@ -31,9 +31,11 @@ import logging
 import numpy
 cimport numpy
 
-cimport cstochasticproxembed
```
Comment (scoder) [inline package/MDAnalysis/analysis/encore/dimensionality_reduction/stochasticproxembed.pyx]: Looks like a relative cimport (instead of this absolute one) would be correct here.

File: package/setup.py [hunk 2]
```diff
@@ -495,11 +485,8 @@ def dynamic_author_list():
           provides=['MDAnalysis'],
           license='GPL 2',
           packages=find_packages(),
-          package_dir={'MDAnalysis': 'MDAnalysis'},
-          ext_package='MDAnalysis',
```
Comment (kain88-de) [inline package/setup.py]: this was the final culprit that lead to setuptools trying to copy to a folder `MDAnalysis/MDAnalysis/...` which doesn't exist. @orbeckst changes broke our expected behavior. I would like to keep it like this now because it's more in line with other projects setup of cython.

File: package/MDAnalysis/analysis/encore/dimensionality_reduction/stochasticproxembed.pyx (hunk 1 above)
Comment (kain88-de) [reply package/MDAnalysis/analysis/encore/dimensionality_reduction/stochasticproxembed.pyx]: good chance might be true. But replacing the pxd file with a single import is better and less code overall.

**Comment by kain88-de** [comment]
The build with cython 0.28 works now.

File: package/MDAnalysis/analysis/encore/dimensionality_reduction/stochasticproxembed.pyx (hunk 1 above)
Comment (orbeckst) [reply package/MDAnalysis/analysis/encore/dimensionality_reduction/stochasticproxembed.pyx]: @mtiberti @wouterboomsma , maybe just double-check that you are not missing anything with inlining the pxd file.

Comment (kain88-de) [reply package/MDAnalysis/analysis/encore/dimensionality_reduction/stochasticproxembed.pyx]: ping @mtiberti  @wouterboomsma

Comment (orbeckst) [reply package/MDAnalysis/analysis/encore/dimensionality_reduction/stochasticproxembed.pyx]: @kain88-de the ENCORE tests pass, don't they?

Let's give @mtiberti and @wouterboomsma another day but if there are no further comments then go ahead and merge.

Comment (mtiberti) [reply package/MDAnalysis/analysis/encore/dimensionality_reduction/stochasticproxembed.pyx]: yep, looks good to me - actually cleaner
