### ISSUE TITLE
mdanalysis wrong dependency

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MDAnalysis/mdanalysis#147]
```
What steps will reproduce the problem?
1. Install biopython 1.58
2. Install MDAnalysis 1.7.7
3. import  MDAnalysis in ipython shell

What is the expected output? What do you see instead?
Error 

---> 50 class SloppyStructureBuilder(Bio.PDB.StructureBuilder.StructureBuilder):
     51     """Cope with resSeq < 10,000 limitation by just incrementing internally.
     52 

AttributeError: 'module' object has no attribute 'StructureBuilder'


What version of the product are you using? On what operating system?
fedora 19 , python 2.7.5 , biopython 1.58 ,madanalysis 1.7.7

Please provide any additional information below.
work fine with biopython 1.61


```

Original issue reported on code.google.com by `baobab...@gmail.com` on 5 Jul 2013 at 3:13
